/* 실제 Chrome과 로컬 중계 연결로 UI·터치 배치·통신 복구를 확인한다. */
'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),assert=require('assert/strict');
const {spawn}=require('child_process');const WebSocket=require('../server/node_modules/ws');
const core=require('../game-core.js');
const upstream=Number(process.argv[2]||18081);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn,ms=7000){const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;await sleep(50);}throw Error('브라우저 조건 대기 시간 초과');}
const links=[];let joined=null,lastWelcome=null,latest=null,browser,cdp,bot;
const proxy=http.createServer((req,res)=>{const q=http.request({host:'127.0.0.1',port:upstream,path:req.url,method:req.method},r=>{res.writeHead(r.statusCode,r.headers);r.pipe(res);});q.on('error',()=>{res.writeHead(502);res.end();});req.pipe(q);});
const wss=new WebSocket.WebSocketServer({server:proxy});
wss.on('connection',down=>{const up=new WebSocket('ws://127.0.0.1:'+upstream);const queue=[];const link={up,down};links.push(link);
  down.on('message',(d,b)=>{if(up.readyState===1)up.send(d,{binary:b});else queue.push([d,b]);});
  up.on('open',()=>{for(const [d,b] of queue)up.send(d,{binary:b});});
  up.on('message',(d,b)=>{if(!b){const m=JSON.parse(d);if(m.t==='joined')joined=m.id;if(m.t==='welcome')lastWelcome=m;}else latest=core.decodeSnapshot(new Uint8Array(d));if(down.readyState===1)down.send(d,{binary:b});});
  down.on('close',code=>{if(up.readyState===1){if(code===1006)up.terminate();else up.close(code===1005?1000:code);}});
  up.on('close',code=>{if(down.readyState===1){if(code===1006)down.terminate();else down.close(code===1005?1000:code);}});
  down.on('error',()=>{});up.on('error',()=>{});
});
(async()=>{
  await new Promise(r=>proxy.listen(0,'127.0.0.1',r));const port=proxy.address().port;
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'soccer-browser-'));
  browser=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','about:blank'],{windowsHide:true,stdio:'ignore'});
  const active=path.join(profile,'DevToolsActivePort');await wait(()=>fs.existsSync(active));const debugPort=Number(fs.readFileSync(active,'utf8').split('\n')[0]);
  const targets=await (await fetch('http://127.0.0.1:'+debugPort+'/json')).json();
  cdp=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>cdp.once('open',r));
  let seq=0;const pending=new Map(),errors=[];
  cdp.on('message',raw=>{const m=JSON.parse(raw);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description || JSON.stringify(m.params.exceptionDetails));});
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});cdp.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result.value;};
  await send('Page.enable');await send('Runtime.enable');await send('Emulation.setFocusEmulationEnabled',{enabled:true});
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await send('Page.navigate',{url:'http://127.0.0.1:'+port+'/?debug=1&touch=1'});
  await wait(()=>evaluate('typeof SoccerCore!=="undefined" && !!SoccerCore.debug'));
  await evaluate('SoccerCore.debug.connect("검증화면")');await wait(()=>lastWelcome);
  await evaluate('document.getElementById("crSize").value="1";document.getElementById("crClassA").value="3";document.getElementById("crClassB").value="7";document.getElementById("crMake").click();true');
  await wait(()=>joined);
  const roomLayout=await evaluate(`(function(){var ids=['rmReady','rmStart','rmLeave'];return ids.map(function(id){var el=document.getElementById(id),r=el.getBoundingClientRect();return {id:id,visible:r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth};});})()`);
  assert(roomLayout.every(r=>r.visible),JSON.stringify(roomLayout));
  let shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('verification/phone-room.png',Buffer.from(shot.data,'base64'));
  bot=new WebSocket('ws://127.0.0.1:'+upstream);let botJoined=false;
  const tell=m=>{if(bot.readyState===1)bot.send(JSON.stringify(m));};
  bot.on('open',()=>tell({t:'hello',v:core.PROTOCOL_VERSION,nick:'검증상대'}));
  bot.on('message',(d,b)=>{if(b)return;const m=JSON.parse(d);if(m.t==='ping')tell({t:'pong',id:m.id});if(m.t==='welcome')tell({t:'room.join',id:joined});if(m.t==='joined'){botJoined=true;tell({t:'ready',on:true});}});
  await wait(()=>botJoined);await evaluate('document.getElementById("rmReady").click();true');
  await wait(()=>evaluate('!document.getElementById("rmStart").disabled'));
  await evaluate('document.getElementById("rmStart").click();true');
  await wait(()=>evaluate('SoccerCore.debug.stats().mode==="online"'));await sleep(3400);
  const firstId=lastWelcome.id,firstLink=links[links.length-1];lastWelcome=null;
  firstLink.down.terminate();firstLink.up.terminate();
  await wait(()=>lastWelcome&&lastWelcome.resumed,10000);
  assert.equal(lastWelcome.id,firstId);await wait(()=>evaluate('SoccerCore.debug.stats().mode==="online"'));
  const label=await evaluate('document.getElementById("rmMembers").textContent');assert(label.includes('3반')&&label.includes('7반'));
  const buttons=await evaluate(`(function(){var bs=Array.from(document.querySelectorAll('.tbtn')).filter(function(e){return getComputedStyle(e).display!=='none';});return bs.map(function(e){var r=e.getBoundingClientRect();return {id:e.id,l:r.left,t:r.top,r:r.right,b:r.bottom};});})()`);
  for(const b of buttons)assert(b.l>=0&&b.r<=390&&b.t>=0&&b.b<=844,JSON.stringify(b));
  for(let i=0;i<buttons.length;i++)for(let j=i+1;j<buttons.length;j++){const a=buttons[i],b=buttons[j];assert(!(Math.min(a.r,b.r)>Math.max(a.l,b.l)&&Math.min(a.b,b.b)>Math.max(a.t,b.t)),a.id+' overlaps '+b.id);}
  shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('verification/phone-match.png',Buffer.from(shot.data,'base64'));
  await evaluate('SoccerCore.debug.practice({teamA:1,teamB:1});true');await sleep(1000);
  assert.equal(await evaluate('SoccerCore.debug.stats().mode'),'practice');
  assert.deepEqual(errors,[]);
  const result={roomActions:roomLayout,touchButtons:buttons.length,overlaps:0,automaticReconnect:true,samePlayerId:true,teamLabels:true,offlineSwitch:true,consoleExceptions:errors};
  fs.writeFileSync('verification/browser.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{if(bot)bot.close(1000);for(const l of links){if(l.down.readyState===1)l.down.close(1000);if(l.up.readyState===1)l.up.close(1000);}if(cdp)cdp.close();if(browser)browser.kill();wss.close();proxy.close();});
